### ISSUE TITLE
[Question] Default MAPF planner: `getAction` 

### ISSUE THREAD

**Issue by miquelramirez** [MAPF-Competition/Start-Kit#69]
My latest submission was reported as crashing on the `large_warehouse_5000` instance and I am tracing the reason for the problem to the function `getAction` in `pibt.cpp`. Please note that I am participating in the `Scheduler` track and using PIBT completely off the shelf.

Below you can see a screenshot of the debugger session, testing on a smaller map, `random-32-32-20`

![image](https://github.com/user-attachments/assets/c7b3d69a-04e1-4199-95d3-bed4d582cadc)

the value of `prev.location` is `886`. All the inputs to this function look, in principle, reasonable as there are no explicit constraints on the values of `next_loc` and `prev.location`.

The variable `orientation` does not get initialized for the specific case shown in the screenshot above e. g. `diff=-103` and the `env->cols` value (32) in the `random-32-32-20` map. I think that is a case it would be good to get a handle on, maybe by doing some precondition check?  This could be just throwing an `std::logic_error` or `std::domain_error` exception with some useful message (e.g. "Precondition check failed: difference between locations is greater than assumed to be possible").

Thanks in advance.

**Comment by nobodyczcz** [comment]
Hi Miquel,

Thanks for this bug report. Yes, I agree this should be handled with some useful error message.

Additionally, may I ask if you have any idea about the context of this error? Since you are working on the scheduler track and not modifying the planner, I think there must be some bug causing a `next_loc` not adjacent to the `prev.location` generated by the planner and then fed to `getAction` function. It would be helpful if you could help me represent the bug on my side.

Best,
Mike

**Comment by miquelramirez** [comment]
Hi Mike,

It was the fault of an earlier version of my scheduler, which wasn't reentrant (I am still not 100% sure it is) and did bad things when interrupted by the simulator. I am not entirely sure what was going, probably the scheduler writing on the memory allocated by the MAPF planner `actions` vector.

Miquel.

**Comment by nobodyczcz** [comment]
We've improved the competition system workflow in the v2.1.0 release.

Best,
Zhe
